#![recursion_limit = "512"]
#![allow(clippy::too_many_arguments)]

pub mod account_service;
pub mod account_worker;
pub mod admin_service;
pub mod api;
pub mod asset_description;
pub mod asset_profiles;
pub mod auth;
pub mod binary_upload;
pub mod briefing_service;
pub mod brunn_state_cli;
pub mod brunn_state_export;
pub mod brunn_state_import;
pub mod config;
pub mod continuation;
pub mod control_service;
pub mod dashboard_service;
pub mod db;
pub mod document_service;
pub mod dreamer;
pub mod dreaming_service;
pub mod embeddings;
pub mod error;
pub mod foreground_latency;
pub mod ingest;
pub mod location;
pub mod logging;
pub mod messaging_protocol;
pub mod messaging_service;
mod migration_checksum_bridge;
mod migration_checksum_map;
pub mod models;
pub mod notification_service;
pub mod object_store;
pub mod operator_service;
pub mod pagination;
pub mod policy;
pub mod quota;
pub mod recurrence;
pub mod refs;
pub mod request_context;
pub mod request_query_count;
pub mod retrieval;
pub mod retrieval_sql;
pub mod secret_service;
pub mod semantic_policy;
pub mod service;
pub mod simple_core;
pub mod simple_worker;
pub mod task_engine;
pub mod task_guard;
pub mod task_service;
pub mod telemetry;
pub mod todoist_sync;
pub mod upload_service;
pub mod usage;
pub mod web_auth;
pub mod worker;
pub mod workspace_features;

pub use api::router;
pub use config::Config;
pub use db::AppState;
pub use error::{ApiError, ApiResult};
